### ISSUE TITLE
Mantenimiento Joel

### ISSUE THREAD

**Issue by guillecchm** [guillecchm/SoftMobileP2#25]
Deberá realizar el mantenimiento de las siguientes clases:
•    Cliente.java
•    TarjetaCredito.java
•    CuentaDAO.java
•    SaldoInsuficienteException.java
•    CuentaInvalidaException.java
•    ClienteNoAutorizadoException.java

**Comment by JoelBau** [comment]
Los cambios han sido introducidos en la rama m_Joel
